### ISSUE TITLE
Feature Request: adaptive image output (as dispatcher option maybe?)

### ISSUE THREAD

**Issue by jvdh** [meenie/munee#33]
Hi Cody,

Great work! Munee has become a standard asset in my projects very quickly.

Previously I experimented with http://adaptive-images.com/ to serve appropriately sized images to devices. I'm trying to find a way to replicate this with munee. 

In short: I'd like to be able to set munee to an exact width (max device screen width) and have it resize all image output to that size. Would a dispacher option work for that?

**Comment by rubenvincenten** [comment]
Hmmm, what if you added the following right after you opened up `<head>`?

```html
<script>document.cookie = "maxwidth=" + screen.width</script>
```
And then added the following to htaccess:
```
RewriteCond %{QUERY_STRING} limitscreen=true [NC]
RewriteCond %{HTTP_COOKIE} maxwidth=(\d+) [NC]
RewriteRule \.(?:jpe?g|gif|png|bmp)$ /$1?resize=w[%1] [QSA,NC]
```

Then in body, assuming bla.jpg is a wallpaper of 1920x1080:
```html
<img src="bla.jpg?limitscreen=true">
```
