### ISSUE TITLE
CSS background relative path problem '//images/img.gif'

### ISSUE THREAD

**Issue by maxicms** [meenie/munee#35]
Hi I have a problem with absolute paths in CSS after running the script in minify CSS opoluchayutsya links with a double slash here is an example:

original: 
background:url(../images/bg.jpg)

after munee:
background:url(//templates/magazine/images/bg.jpg)

because excess slash pictures are not loaded

**Comment by meenie** [comment]
Please open this back up if you are having anymore issues.
