### ISSUE TITLE
Javascript Minify : problem with comments

### ISSUE THREAD

**Issue by WilliamVercken** [meenie/munee#38]
Hi ! I found an issue with the minify command when there is a comment at the bottom of js files.

### /media/js/test1.js
```js
//TEST1
alert('TEST 1');
//END TEST1
```
### /media/js/test2.js
```js
//TEST2
alert('TEST 2');
//END TEST2
```
### Combine without Minify : OK
```html
<script type="text/javascript" src="/munee.php?files=/media/js/test1.js,/media/js/test2.js" defer></script>
```
```js
//TEST1
alert('TEST 1');
//END TEST1
//TEST2
alert('TEST 2');
//END TEST2
```
### Combine & Minify : NOT OK
```html
<script type="text/javascript" src="/munee.php?files=/media/js/test1.js,/media/js/test2.js&minify=true" defer></script>
```
```js
alert('TEST 1');END TEST1

alert('TEST 2');END TEST2
```

**Comment by meenie** [comment]
I just tried this and had no issues.  I've recently updated the jsmin library to it's latest version. It could have been an issue in the previous version.  Thanks for the report!
