### ISSUE TITLE
Apache mod_aliased asset files are reporting not found

### ISSUE THREAD

**Issue by xiphiaz** [meenie/munee#41]
If I have my asset files outside of the site's webroot, reference via mod_alias, munee throws a NotFoundException as it can't find the file due to file_exists referencing the wrong webroot.

Is there an option to have munee load the files by using the existing rewrite rules, eg a curl loopback would return the file based on an alias (though there might be an infinite loop with munee...)

**Comment by meenie** [comment]
I'm in agreement with @rubenvincenten.  @xiphiaz please reopen if you are still having issues.
