### ISSUE TITLE
attribute selectors and extend bug

### ISSUE THREAD

**Issue by aronduby** [meenie/munee#46]
Using attribute ends with selector with extend is getting output as junk. Here's my usage:

```scss
.content-item{
  /* styles for content-item */

  h1{
    /* styles for content-item h1 */

    a::after{ @extend .fa; } /* this works */
    a[href$=".pdf"]:after{ /* this breaks everything */
      @extend .fa-file-pdf-o:before;
    }
  }
}
```

I'm expecting the `a[href$="pdf"]:after` selector to end up being:

```scss
.fa-file-pdf-o:before, 
.content-item h1 a[href$="pdf"]:after
``` 

but instead it gets mashed into:
```scss
.fa-file-pdf-o:before, 
.content-item h1 ".pdf"][href$=:after
```

**Comment by meenie** [comment]
@aronduby I'm sorry this is so late.  I've updated the SCSS library to the latest version and your SCSS is now outputting correctly.  You can view the fix here: #69
