### ISSUE TITLE
+FIX less component doesn't work with data-uri e,g, base 64 encoded SVG

### ISSUE THREAD

**Issue by a2d** [meenie/munee#50]
url(data:...) get treated as relative path since it doesn't start with slash or dot.

Fix: change line 175 in munee/meenie/munie/src/Munie/Asset/Type/Css.php

from: if ($filePath[0] !== '/') {

to: if ($filePath[0] !== '/' && substr($filePath,0,5) !== 'data:') {

Save. Don't forget it won't seem to work until you make a change to the source less file your'e trying to process (since there's caching)

**Comment by meenie** [comment]
This has been fixed in #66.  Thanks for posting your workaround :).
