### ISSUE TITLE
extension not handled?

### ISSUE THREAD

**Issue by tmblog** [meenie/munee#58]
I am getting this error
Error: The following extension is not handled: jpg?resize=width[250]

This is how I am referencing the file:

<img src="munee.php?files=images/an_image.jpg?resize=width[250]" />

Is that the correct way to call it?

**Comment by meenie** [comment]
You have to do `<img src="munee.php?files=images/an_image.jpg&resize=width[250]" />`.  You'll notice that you can't have two `?`.  Each query param after the first one needs to be delimited by a `&`.

**Comment by meenie** [comment]
Please re-open if this doesn't fix your issue.

**Comment by tmblog** [comment]
Excellent, daft oversight in my part. Thank you! Excellent script btw!

**Comment by meenie** [comment]
No worries :).
