### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by webbird** [meenie/munee#61]
Yesterday I tried to use the minify-Filter with JS and found that I need to install JShrink. I did not find this in the docs.

**Comment by meenie** [comment]
It should have already been installed through Composer: https://github.com/meenie/munee/blob/65b09b8e0247523d14a2920ed09e4a0b9cbdba3e/composer.json#L24

Is that not happening?

**Comment by webbird** [comment]
I installed manually. Not everyone uses Composer. ;)

**Comment by dkcwd** [comment]
Any good reason they don't? :-)

**Comment by webbird** [comment]
Short answer: Yes.

In fact, it _is_ a dependency, so it should be documented, shouldn't it?

Well, your decision.

**Comment by dkcwd** [comment]
You could send a pull request through to add that to the readme file. If you are unsure how to do it let me know and I'll be happy to help.

**Comment by dkcwd** [comment]
Actually it had been a while since I had looked at the documentation and
there is installation information for a .zip for anyone not using composer
at http://mun.ee/Installating_Munee/Using_Zip_File and it contains JShrink.

Did you see that page?

**Comment by webbird** [comment]
Yes, the ZIP contains lots of stuff, but not the docs. But hey, if it's too much effort to just add a note, just forget it.

**Comment by dkcwd** [comment]
One of the great things about open source is that anyone can own
maintenance and make suggestions.
I saw your comment and thought I'd join a conversation.
On seeing your next response I thought it was appropriate to suggest a way
you could get involved.
You went through an experience where you couldn't find some information
which you think people would find helpful.
I reckon you will understand where in the documentation it would make sense
to add that information.

I didn't create the library and I'm not an official maintainer but I or
anyone else can navigate to the documentation link, fork the documentation
project and suggest a change via a pull request.
I'm happy to help if you're unsure of how to do that and I'm sorry if you
think I was having a go at you or something, that's definitely not the case.
Let me know if you want some help.

Cheers,
Dave
