### ISSUE TITLE
Bad Value for SRC

### ISSUE THREAD

**Issue by tmblog** [meenie/munee#77]
In the html validator it is considered a bad value to have: 

`munee.php?files=images/image.jpg&resize=width[750]q[99] for attribute src on element img: Illegal character in query: not a URL code point.`

Is there a work around for this?

**Comment by meenie** [comment]
If you really need it to pass HTML Validation, you could run the string through `urlencode()` in php.  Which would give you the string `munee.php%3Ffiles%3Dimages%2Fimage.jpg%26resize%3Dwidth%5B750%5Dq%5B99%5D`.

**Comment by meenie** [comment]
@tmblog: Please reopen this issue if you are still having issues.
