### ISSUE TITLE
Concatenating Text Assets Not Functioning

### ISSUE THREAD

**Issue by JasonAlanKennedy** [meenie/munee#85]
*This doesn't make sense to me being that concatenation is the biggest feature of Munee. For some reason it is not functioning in my use. I don't see any past issues reported so I reverted to v1.6.0 and no change.*

*Below is my example usage.*

***NOTE***: I haven't tried JS

---
**PHP:**

    <?php
    define('WEBROOT', $_SERVER['DOCUMENT_ROOT']);
    define('MUNEE_CACHE', $_SERVER['DOCUMENT_ROOT'] . '/.cache/assets/');
    require $_SERVER['DOCUMENT_ROOT'] . '/_core/vendor/autoload.php';
    echo \Munee\Dispatcher::run(new \Munee\Request());

**htaccess:**

    RewriteRule ^(.*\.(?:css|less|scss|js|coffee|jpg|png|gif|jpeg))$ _core/munee.php?files=/$1 [L,QSA,NC]
---
**Usage:**

    <link rel="stylesheet" href="/css/sheet01.css,/css/sheet02.css">
    
**Expected Output:**

2. Rewrite rule to redirect to munee.php
3. Stylesheets to be concatenated and cached
4. Send cached stylesheets to client

**Actual Output:**

1. Rewrite rule to redirect to munee.php
2. Stylesheets ARE NOT concatenated and cached
3. Status Code:404 Not Found: https://site.com/css/sheet01.css,/css/sheet02.css
4. Images & JS ARE cached

---

**What Works:**

    <link rel="stylesheet" href="/css/sheet01.css">
    // And...
    <link rel="stylesheet" href="/css/sheet01.css?minify=true">

---

*Something I have wronge somewhere?*

*Thnx for your help*

**-j**

**Comment by meenie** [comment]
Does `<link rel="stylesheet" href="/css/sheet02.css">` work? Just making sure you second stylesheet exists :)

**Comment by JasonAlanKennedy** [comment]
Yes they do, thnx.

**Comment by meenie** [comment]
Have you tried it without using the RewriteRule? 

`<link rel="stylesheet" href="/_core/munee.php?files=/css/sheet01.css,/css/sheet02.css">`

**Comment by JasonAlanKennedy** [comment]
Sorry, I hade to move on to another product.
