### ISSUE TITLE
Need to refresh twice in order for it for work

### ISSUE THREAD

**Issue by waiylgeek** [meenie/munee#90]
At first impression it doesn't compile the assets, I have to refresh the page twice in order for it to work!

**Comment by meenie** [comment]
It should be setting the correct `etag` headers to make sure it busts the cache on every render.  If the etag matches the hash of the content, munee returns a 304.  If the etag has changed, then it should return the new content.  Can you open up your network panel to see if that is happening? Check to see if your request headers include a `If-None-Match` entry.

**Comment by meenie** [comment]
If you need more information on how caching works in the browser, have a read of this article: https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers

**Comment by meenie** [comment]
Closing this out.  If you are still having issues, please re-open :).
