### ISSUE TITLE
API site is down

### ISSUE THREAD

**Issue by ArturGrigio** [meenie/munee#94]
Hey guys, 
The API site is down, would you mind listing the API on the GitHub repo?

BTW, thanks for the tool.

**Comment by meenie** [comment]
Looks like my server is not working. I'll have it back up soon.

**Comment by meenie** [comment]
@ArturGrigio: I've put the site on Heroku. Use this url for now: http://munee.herokuapp.com/

**Comment by meenie** [comment]
I've finally got the domain http://mun.ee to point to Heroku. Closing this off.
