### ISSUE TITLE
69.191.249.213 ip keep accessing through munee.php

### ISSUE THREAD

**Issue by stanley87** [meenie/munee#99]
Hi munee team, is that this ip 69.191.249.213 belongs to munee plugin for any purpose ? tracking ?
Kindly let me know if this ip not using by munee plugin so that my side can block for security reason.

Thanks

**Comment by stanley87** [comment]
<img width="729" alt="screen shot 2016-11-12 at 10 42 22 pm" src="https://cloud.githubusercontent.com/assets/5809683/20238590/d6c8b0e0-a929-11e6-9ac4-8d831111fc2f.png">

**Comment by meenie** [comment]
That has nothing to do with munee, block away.

**Comment by stanley87** [comment]
Thanks for swift confirmation.
